version: '3.3'
services:
    postgres:
        image: postgres:alpine 
        ports:
            - 5432:5432
        restart: always
        env_file:
            - ./config/dev.env
        volumes:
            - posts-postgres:/var/lib/postgresql/data
    api:
        build: ./services/api
        working_dir: /app
        volumes:
            - ./services/api:/app
            - /app/node_modules
        env_file:
            - ./config/dev.env
        depends_on: 
            - postgres
    ui:
        build: ./services/ui
        working_dir: /app
        env_file:
            - ./config/dev.env
        volumes:
            - ./services/ui:/app
            - /app/node_modules
        command: sleep infinity
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - 80:80
        volumes:
            - ./services/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
            - ./services/api/src/public:/var/www/public:ro
volumes:
    posts-postgres: